POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Marta Williams",
    "number": "33-12-3236643"
}

###
# testing post on deployed backend
POST https://phonebook-cgze.onrender.com/api/persons
content-type: application/json

{
    "name": "Marta Williams",
    "number": "33-123236643"
}