POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Marta Williams",
    "number": "1-125343443"
}


###
# testing post on deployed backend
POST https://phonebook-cgze.onrender.com/api/persons
content-type: application/json

{
    "name": "Brian Wheeler",
    "number": "44-1234664554"
}