GET http://localhost:3001/api/persons/

###
# to test unkown endpoint middleware
GET http://localhost:3001/api/pearsons

###
# testing deployed backend
GET https://phonebook-cgze.onrender.com/api/persons